apiVersion: apps/v1
kind: Deployment
metadata:
  name: vulnerable-log4j-app
  labels:
    app: vulnerable-log4j-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vulnerable-log4j-app
  template:
    metadata:
      labels:
        app: vulnerable-log4j-app
    spec:
      containers:
      - name: vulnerable-log4j-app
        image: quay.io/vicenteherrera/log4shell-vulnerable-app
        ports:
        - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: vulnerable-log4j
spec:
  selector:
    app: vulnerable-log4j-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
